
DROP FUNCTION IF EXISTS llista_esports();

CREATE OR REPLACE FUNCTION llista_esports()
RETURNS TABLE(cod integer, nom varchar) AS $$
BEGIN
    RETURN QUERY
    SELECT COD, NOMBRE FROM DEPORTES ORDER BY COD;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS DEPORTES (
    COD serial PRIMARY KEY,
    NOMBRE varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS ATLETAS (
    COD serial PRIMARY KEY,
    NOMBRE varchar NOT NULL,
    DEPORTE_COD integer REFERENCES DEPORTES(COD)
);

CREATE TABLE IF NOT EXISTS users (
    id serial PRIMARY KEY,
    username varchar NOT NULL,
    password varchar NOT NULL
);

INSERT INTO users(username, password)
SELECT 'alumne', '1234' WHERE NOT EXISTS (SELECT 1 FROM users WHERE username='alumne');

INSERT INTO DEPORTES(NOMBRE)
SELECT 'Futbol' WHERE NOT EXISTS (SELECT 1 FROM DEPORTES WHERE NOMBRE='Futbol');
INSERT INTO DEPORTES(NOMBRE)
SELECT 'Natació' WHERE NOT EXISTS (SELECT 1 FROM DEPORTES WHERE NOMBRE='Natació');
INSERT INTO DEPORTES(NOMBRE)
SELECT 'Atletisme' WHERE NOT EXISTS (SELECT 1 FROM DEPORTES WHERE NOMBRE='Atletisme');

INSERT INTO ATLETAS(NOMBRE, DEPORTE_COD)
SELECT 'Joan' , d.COD FROM DEPORTES d WHERE d.NOMBRE='Futbol' AND NOT EXISTS (SELECT 1 FROM ATLETAS a WHERE a.NOMBRE='Joan');
INSERT INTO ATLETAS(NOMBRE, DEPORTE_COD)
SELECT 'Anna' , d.COD FROM DEPORTES d WHERE d.NOMBRE='Natació' AND NOT EXISTS (SELECT 1 FROM ATLETAS a WHERE a.NOMBRE='Anna');
INSERT INTO ATLETAS(NOMBRE, DEPORTE_COD)
SELECT 'Pere' , d.COD FROM DEPORTES d WHERE d.NOMBRE='Atletisme' AND NOT EXISTS (SELECT 1 FROM ATLETAS a WHERE a.NOMBRE='Pere');

DROP FUNCTION IF EXISTS llista_atletes(integer);
CREATE OR REPLACE FUNCTION llista_atletes(p_esport_id integer)
RETURNS TABLE(cod integer, nom varchar, esport_nom varchar) AS $$
BEGIN
    RETURN QUERY
    SELECT a.COD, a.NOMBRE, d.NOMBRE
    FROM ATLETAS a
    LEFT JOIN DEPORTES d ON a.DEPORTE_COD = d.COD
    WHERE a.DEPORTE_COD = p_esport_id
    ORDER BY a.COD;
END;
$$ LANGUAGE plpgsql;

DROP FUNCTION IF EXISTS buscar_atletes(text);
CREATE OR REPLACE FUNCTION buscar_atletes(p_cadena text)
RETURNS TABLE(cod integer, nom varchar, esport_nom varchar) AS $$
BEGIN
    RETURN QUERY
    SELECT a.COD, a.NOMBRE, d.NOMBRE
    FROM ATLETAS a
    LEFT JOIN DEPORTES d ON a.DEPORTE_COD = d.COD
    WHERE LOWER(a.NOMBRE) LIKE '%' || LOWER(p_cadena) || '%'
    ORDER BY a.COD;
END;
$$ LANGUAGE plpgsql;
